# Generated by Django 2.2.4 on 2023-12-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20231202_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Email', models.CharField(max_length=45)),
                ('Number', models.IntegerField()),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('barber1', models.CharField(max_length=45)),
                ('barber2', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Book1',
        ),
    ]
