# Generated by Django 2.2.4 on 2023-12-02 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20231202_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Barber',
        ),
    ]
