# Generated by Django 2.2.4 on 2023-12-02 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_book_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
